print("1 Sou um programa Python!")
print("2 Sou um programa Python!")
print("3 Sou um programa Python!")
print("4 Sou um programa Python!")
print("5 Sou um programa Python!")
print("6 Sou um programa Python!")
print("7 Sou um programa Python!")
print("8 Sou um programa Python!")
print("9 Sou um programa Python!")
print("10 Sou um programa Python!")

